### PR TITLE
Add evidence of MIT relicense

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
https://gitlab.com/coala/package_manager/merge_requests/94 has been merged, with all approvers retained.  The repo MR rules were modified temporarily to allow the approvers to be retained with the rebase, and to merge without CI passing.  The old settings have been re-enabled.

**Comment by Makman2** [comment]
ack a00120ec5cb6a85f74123ab3668f07cecbf7b9ee

**Comment by Makman2** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
Hey! I'm [GitMate.io](https://gitmate.io)! This pull request is being fastforwarded automatically. Please **DO NOT** push while fastforward is in progress or your changes would be lost permanently :warning:

**Comment by jayvdb** [comment]
Automated fastforward with [GitMate.io](https://gitmate.io) was successful! :tada:

**Pull request merged**
